version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: extension-management:latest
    container_name: extension-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RDS_HOST: ${RDS_HOST}
      RDS_PORT: ${RDS_PORT}
      RDS_DB_NAME: ${RDS_DB_NAME}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
