server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/extension_db?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    root: WARN