-- src/main/resources/schema.sql
CREATE TABLE extension (
                           id          BIGINT
                               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name        VARCHAR(20)  NOT NULL,
                           type        VARCHAR(20)  NOT NULL,
                           enabled     BOOLEAN      NOT NULL,
                           created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP()
);
